version: 2.1
orbs:
    node: circleci/node@1.1.6
jobs:
    build-and-test:
        executor:
            name: node/default
        steps:
            - checkout
            - persist_to_workspace:
            - node/with-cache:
                steps:
                    - run: npm install
                    - run: npm run deploy-storybook -- --ci
workflows:
    build-and-test:
        jobs:
            - build-and-test